# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco
jobs:
- job: 'MonoGameMac'
  displayName: 'Mac'
  variables:
    - group: 'Keys'

  pool:
    vmImage: 'macOS-10.15'
    demands: msbuild

  steps:
  - checkout: self
    submodules: 'true'

  - template: common-dotnet.yml@templates
  - template: common-macos.yml@templates

  - task: NuGetCommand@2 #MonoGame.Framework/MonoGame.Framework.iOS.csproj
    displayName: 'NuGet restore  MonoGame.Framework/MonoGame.Framework.iOS.csproj'
    inputs:
      restoreSolution: ./MonoGame.Framework/MonoGame.Framework.iOS.csproj

  - task: NuGetCommand@2
    displayName: 'NuGet restore  MonoGame.Framework.DesktopGL.Mac.csproj'
    inputs:
      restoreSolution: ./MonoGame.Framework/MonoGame.Framework.DesktopGL.Mac.csproj

  - task: PowerShell@2
    displayName: 'PreBuild'
    inputs:
      targetType: filePath
      filePath: ./devops/PreBuild.ps1
      pwsh: true

  # Build  MonoGame

  - task: MSBuild@1 # Fantas.MonoGame.sln
    displayName: 'Build csproj ./MonoGame.Framework/MonoGame.Framework.iOS.csproj'
    inputs:
      solution: ./MonoGame.Framework/MonoGame.Framework.iOS.csproj
      configuration: Release

  - task: MSBuild@1 # Xam.Mac build
    displayName: 'Build csproj ./MonoGame.Framework/MonoGame.Framework.DesktopGL.Mac.csproj'
    inputs:
      solution: ./MonoGame.Framework/MonoGame.Framework.DesktopGL.Mac.csproj
      configuration: Release

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact: Xamarin.Mac.MonoGame.Frawework'
    inputs:
      targetPath: ./Artifacts/MonoGame.Framework/DesktopGL.Mac/Release/xamarinmac20/
      artifact: 'Xamarin.Mac.MonoGame.Frawework'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact: Xamarin.iOS.MonoGame.Frawework'
    inputs:
      targetPath: ./Artifacts/MonoGame.Framework/iOS/Release/xamarinios10/
      artifact: 'Xamarin.iOS.MonoGame.Frawework'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact: Xamarin.tvOS.MonoGame.Frawework'
    inputs:
      targetPath: ./Artifacts/MonoGame.Framework/iOS/Release/xamarintvos10/
      artifact: 'Xamarin.tvOS.MonoGame.Frawework'
      publishLocation: 'pipeline'

  - template: send-telegram.yml@templates

- job: 'MonoGameWindows'
  displayName: 'Windows'
  dependsOn: 'MonoGameMac'
  variables:
    - group: 'Keys'

  pool:
    vmImage: 'windows-2019'
    demands:
    - msbuild
    - visualstudio
    - vstest

  steps:
  - checkout: self
    submodules: true

  - template: common-dotnet.yml@templates
  - template: common-win.yml@templates

  - task: NuGetCommand@2
    displayName: 'NuGet restore  MonoGame.Framework.Android.csproj'
    inputs:
      restoreSolution: ./MonoGame.Framework/MonoGame.Framework.Android.csproj

  - task: NuGetCommand@2
    displayName: 'NuGet restore MonoGame.Framework.DesktopGL.csproj'
    inputs:
      restoreSolution: ./MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj

  - task: NuGetCommand@2
    displayName: 'NuGet restore MonoGame.Framework.WindowsDX'
    inputs:
      restoreSolution: ./MonoGame.Framework/MonoGame.Framework.WindowsDX.csproj

  - task: NuGetCommand@2
    displayName: 'NuGet restore MonoGame.Framework.WindowsUniversal.csproj'
    inputs:
      restoreSolution: ./MonoGame.Framework/MonoGame.Framework.WindowsUniversal.csproj

  - task: PowerShell@2
    displayName: 'PreBuild Script MonoGame'
    inputs:
      targetType: filePath
      filePath: ./devops/PreBuild.ps1
      errorActionPreference: 'silentlyContinue'
      pwsh: true

  - task: MSBuild@1
    displayName: 'Build csproj ./MonoGame.Framework/MonoGame.Framework.Android.csproj'
    inputs:
      solution: ./MonoGame.Framework/MonoGame.Framework.Android.csproj
      configuration: Release

  - task: MSBuild@1
    displayName: 'Build csproj ./MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj'
    inputs:
      solution: ./MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj
      configuration: Release

  - task: MSBuild@1
    displayName: 'Build csproj ./MonoGame.Framework/MonoGame.Framework.WindowsDX.csproj'
    inputs:
      solution: ./MonoGame.Framework/MonoGame.Framework.WindowsDX.csproj
      configuration: Release

  - task: MSBuild@1
    displayName: 'Build csproj ./MonoGame.Framework/MonoGame.Framework.WindowsUniversal.csproj'
    inputs:
      solution: ./MonoGame.Framework/MonoGame.Framework.WindowsUniversal.csproj
      configuration: Release

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Build Xamarin.iOS'
    inputs:
      buildType: 'current'
      artifactName: 'Xamarin.iOS.MonoGame.Frawework'
      targetPath: './Artifacts/MonoGame.Framework/iOS/Release/xamarinios10/'

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Build Xamarin.tvOS'
    inputs:
      buildType: 'current'
      artifactName: 'Xamarin.tvOS.MonoGame.Frawework'
      targetPath: './Artifacts/MonoGame.Framework/iOS/Release/xamarintvos10/'

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Build Xamarin.Mac'
    inputs:
      buildType: 'current'
      artifactName: 'Xamarin.Mac.MonoGame.Frawework'
      targetPath: './Artifacts/MonoGame.Framework/DesktopGL.Mac/Release/xamarinmac20/'

  - script: 'nuget setapikey $(apikey)'
    displayName: 'Set NuGet API Key'

  - task: PowerShell@2
    displayName: 'Package Codefoco.MonoGame.Framework.nuget NuGet'
    inputs:
      targetType: filePath
      filePath: ./devops/Package.ps1
      arguments: 'Codefoco.MonoGame.Framework'
      pwsh: true

  - task: PowerShell@2
    displayName: 'Package Codefoco.MonoGame.Framework.WindowsDX.nuget NuGet'
    inputs:
      targetType: filePath
      filePath: ./devops/Package.ps1
      arguments: 'Codefoco.MonoGame.Framework.WindowsDX'
      pwsh: true

  - task: PublishBuildArtifacts@1
    displayName: 'Save Codefoco.MonoGame.Framework.nupkg Artifact'
    inputs:
      PathtoPublish: Codefoco.MonoGame.Framework.nupkg
      ArtifactName: Codefoco.MonoGame.Framework.nupkg

  - task: PublishBuildArtifacts@1
    displayName: 'Save Codefoco.MonoGame.Framework.snupkg Artifact'
    inputs:
      PathtoPublish: Codefoco.MonoGame.Framework.snupkg
      ArtifactName: Codefoco.MonoGame.Framework.snupkg

  - task: PublishBuildArtifacts@1
    displayName: 'Save Codefoco.MonoGame.Framework.WindowsDX.nupkg Artifact'
    inputs:
      PathtoPublish: Codefoco.MonoGame.Framework.WindowsDX.nupkg
      ArtifactName: Codefoco.MonoGame.Framework.WindowsDX.nupkg

  - task: PublishBuildArtifacts@1
    displayName: 'Save Codefoco.MonoGame.Framework.WindowsDX.snupkg Artifact'
    inputs:
      PathtoPublish: Codefoco.MonoGame.Framework.WindowsDX.snupkg
      ArtifactName: Codefoco.MonoGame.Framework.WindowsDX.snupkg

  - task: PowerShell@2
    displayName: 'Publish Codefoco.MonoGame.Framework NuGet'
    inputs:
      targetType: filePath
      filePath: ./devops/Publish.ps1
      arguments: Codefoco.MonoGame.Framework.WindowsDX
      pwsh: true

  - task: PowerShell@2
    displayName: 'Publish Codefoco.MonoGame.Framework NuGet'
    inputs:
      targetType: filePath
      filePath: ./devops/Publish.ps1
      arguments: Codefoco.MonoGame.Framework
      pwsh: true

  - template: send-telegram.yml@templates
